name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Build e testes
        run: ./gradlew build

      - name: Salvar JAR
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar