name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Testes
        run: ./gradlew test

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem Docker
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/demo-project:latest \
            -t ghcr.io/${{ github.repository_owner }}/demo-project:${{ github.sha }} \
            .

      - name: Push da imagem
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/demo-project:latest
          docker push ghcr.io/${{ github.repository_owner }}/demo-project:${{ github.sha }}