name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: demo
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Subir PostgreSQL
        run: docker compose up -d postgres

      - name: Aguardar PostgreSQL
        run: |
          until docker compose exec -T postgres pg_isready -U postgres -d demo; do
            echo "Aguardando PostgreSQL..."
            sleep 2
          done

      - name: Build e testes
        run: ./gradlew build

      - name: Salvar JAR
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: build/libs/*.jar

      - name: Derrubar containers
        if: always()
        run: docker compose down